# Generated by Django 5.2.6 on 2025-09-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('MAQUIAGEM', 'Maquiagem'), ('SKINCARE', 'SkinCare'), ('CABELO', 'Cabelo'), ('OUTROS', 'Outros')], max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
