# Generated by Django 5.2.6 on 2025-09-28 23:25

import core.models.tipo
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='categoria',
            field=models.ForeignKey(default=core.models.tipo.get_default_categoria, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='core.category'),
        ),
    ]
