# Generated by Django 5.2.6 on 2025-10-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_colecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.category')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.colecao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.tipo')),
            ],
        ),
    ]
