# Generated by Django 5.2.6 on 2025-10-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_amostra',
            field=models.ImageField(blank=True, null=True, upload_to='amostras/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_produto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
