# Generated by Django 5.2.6 on 2025-10-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_produto_imagem_produto_imagem_amostra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
