# Generated by Django 5.2.6 on 2025-10-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_purchase_options_purchase_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total da Compra'),
        ),
    ]
